/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 26 13:24:15 GMT 2026
 */

package it.uniroma2.isw2.openjpa.testing.listiteratorwrapper.es;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Iterator;
import java.util.NoSuchElementException;
import org.apache.openjpa.lib.util.collections.ListIteratorWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class ListIteratorWrapperEvoSuiteSeed0Test extends ListIteratorWrapperEvoSuiteSeed0Scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(integer0).when(iterator0).next();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      listIteratorWrapper0.next();
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      listIteratorWrapper1.remove();
      assertFalse(listIteratorWrapper1.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(1151);
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(integer0).when(iterator0).next();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      listIteratorWrapper0.next();
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      listIteratorWrapper1.reset();
      assertFalse(listIteratorWrapper1.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Iterator<Object> iterator0 = (Iterator<Object>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      try { 
        listIteratorWrapper1.set(listIteratorWrapper0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // ListIteratorWrapper does not support optional operations of ListIterator.
         //
         verifyException("org.apache.openjpa.lib.util.collections.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Iterator<Object> iterator0 = (Iterator<Object>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null, (Object) null).when(iterator0).next();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      listIteratorWrapper0.next();
      listIteratorWrapper0.next();
      listIteratorWrapper0.reset();
      // Undeclared exception!
      try { 
        listIteratorWrapper0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot remove element at index 0.
         //
         verifyException("org.apache.openjpa.lib.util.collections.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      // Undeclared exception!
      try { 
        listIteratorWrapper1.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot remove element at index -1.
         //
         verifyException("org.apache.openjpa.lib.util.collections.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      int int0 = listIteratorWrapper1.previousIndex();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null, (Object) null).when(iterator0).next();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      listIteratorWrapper0.next();
      listIteratorWrapper0.next();
      listIteratorWrapper0.previous();
      Integer integer0 = listIteratorWrapper0.previous();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      try { 
        listIteratorWrapper1.previous();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.lib.util.collections.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      int int0 = listIteratorWrapper1.nextIndex();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(integer0).when(iterator0).next();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      listIteratorWrapper0.next();
      listIteratorWrapper0.previous();
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      Object object0 = listIteratorWrapper1.next();
      assertEquals((-1), object0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(integer0).when(iterator0).next();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      assertFalse(listIteratorWrapper0.hasPrevious());
      
      listIteratorWrapper0.next();
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      boolean boolean0 = listIteratorWrapper1.hasPrevious();
      assertTrue(boolean0);
      assertTrue(listIteratorWrapper0.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Iterator<Integer> iterator0 = (Iterator<Integer>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      boolean boolean0 = listIteratorWrapper1.hasPrevious();
      assertFalse(boolean0);
  }
}
