/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package it.uniroma2.isw2.openjpa.testing.pcenhancer.mt;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.Externalizable;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;

import org.apache.openjpa.conf.OpenJPAConfigurationImpl;
import org.apache.openjpa.enhance.PCEnhancer;
import org.apache.openjpa.enhance.PersistenceCapable;
import org.apache.openjpa.meta.ClassMetaData;
import org.junit.jupiter.api.Test;

/**
 * TMT-003.
 *
 * Mutation-guided behavioral test for the standard Java Serialization path
 * generated by PCEnhancer.
 *
 * The oracle verifies a real ObjectOutputStream/ObjectInputStream round-trip
 * of an enhanced Serializable entity.
 */
class PCEnhancerMutationSerializationTest {

    private static final String TARGET_NAME =
            PCEnhancerMutationSerializationTarget.class.getName();

    @Test
    void generatedSerializationMethodsPreserveRuntimeState()
            throws Exception {

        OpenJPAConfigurationImpl configuration =
                new OpenJPAConfigurationImpl();

        Path output =
                Files.createTempDirectory(
                        "pcenhancer-tmt003-");

        try {

            configuration.setLog(
                    "File=stdout, DefaultLevel=WARN");

            configuration.setMetaDataFactory(
                    "jpa");

            PCEnhancer enhancer =
                    new PCEnhancer(
                            configuration,
                            PCEnhancerMutationSerializationTarget.class);

            ClassMetaData metadata =
                    enhancer.getMetaData();

            assertNotNull(
                    metadata,
                    "Persistence metadata must be available.");

            /*
             * Preconditions identifying the standard Java Serialization
             * enhancement path.
             */
            assertTrue(
                    Serializable.class.isAssignableFrom(
                            PCEnhancerMutationSerializationTarget.class),
                    "Target must be Serializable.");

            assertFalse(
                    Externalizable.class.isAssignableFrom(
                            PCEnhancerMutationSerializationTarget.class),
                    "Target must not already be Externalizable.");

            assertNull(
                    metadata.getDetachedState(),
                    "Target must not use synthetic detached state.");

            assertFalse(
                    enhancer.getCreateSubclass(),
                    "Test must exercise normal enhancement.");

            assertFalse(
                    enhancer.getRedefine(),
                    "Test must not exercise redefine mode.");

            enhancer.setDirectory(
                    output.toFile());

            assertEquals(
                    PCEnhancer.ENHANCE_PC,
                    enhancer.run(),
                    "Target must require persistence-capable enhancement.");

            enhancer.record();

            Path enhancedClass =
                    output.resolve(
                            TARGET_NAME.replace(
                                    '.',
                                    File.separatorChar)
                                    + ".class");

            assertTrue(
                    Files.isRegularFile(enhancedClass),
                    "Enhanced class must be recorded.");

            /*
             * Load the enhanced bytes rather than the original fixture
             * already loaded by the test JVM.
             */
            try (ChildFirstTargetLoader loader =
                         new ChildFirstTargetLoader(
                                 new URL[]{
                                         output.toUri().toURL()
                                 },
                                 PCEnhancerMutationSerializationTarget
                                         .class
                                         .getClassLoader(),
                                 TARGET_NAME)) {

                Class<?> enhancedType =
                        Class.forName(
                                TARGET_NAME,
                                true,
                                loader);

                assertTrue(
                        PersistenceCapable.class.isAssignableFrom(
                                enhancedType),
                        "Recorded class must be persistence-capable.");

                assertTrue(
                        Serializable.class.isAssignableFrom(
                                enhancedType),
                        "Enhanced class must remain Serializable.");

                assertFalse(
                        Externalizable.class.isAssignableFrom(
                                enhancedType),
                        "Standard Serialization must remain distinct "
                                + "from Externalization.");

                /*
                 * PCEnhancer must have generated the two private Java
                 * Serialization hooks.
                 */
                assertNotNull(
                        enhancedType.getDeclaredMethod(
                                "writeObject",
                                ObjectOutputStream.class),
                        "Generated writeObject(ObjectOutputStream) "
                                + "must exist.");

                assertNotNull(
                        enhancedType.getDeclaredMethod(
                                "readObject",
                                ObjectInputStream.class),
                        "Generated readObject(ObjectInputStream) "
                                + "must exist.");

                Object source =
                        enhancedType
                                .getDeclaredConstructor()
                                .newInstance();

                var setId =
                        enhancedType.getMethod(
                                "setId",
                                long.class);

                var setCounter =
                        enhancedType.getMethod(
                                "setCounter",
                                int.class);

                var setLabel =
                        enhancedType.getMethod(
                                "setLabel",
                                String.class);

                var getId =
                        enhancedType.getMethod(
                                "getId");

                var getCounter =
                        enhancedType.getMethod(
                                "getCounter");

                var getLabel =
                        enhancedType.getMethod(
                                "getLabel");

                /*
                 * Distinguishable state values make loss/corruption during
                 * serialization observable.
                 */
                setId.invoke(
                        source,
                        17L);

                setCounter.invoke(
                        source,
                        314159);

                setLabel.invoke(
                        source,
                        "SER-A");

                byte[] payload;

                try (ByteArrayOutputStream bytes =
                             new ByteArrayOutputStream();
                     ObjectOutputStream out =
                             new ObjectOutputStream(bytes)) {

                    out.writeObject(
                            source);

                    out.flush();

                    payload =
                            bytes.toByteArray();
                }

                assertTrue(
                        payload.length > 0,
                        "Serialization must produce a non-empty payload.");

                Object restored;

                try (LoaderObjectInputStream in =
                             new LoaderObjectInputStream(
                                     new ByteArrayInputStream(
                                             payload),
                                     loader)) {

                    restored =
                            in.readObject();
                }

                assertNotNull(
                        restored,
                        "Deserialization must produce an object.");

                assertSame(
                        enhancedType,
                        restored.getClass(),
                        "Deserialization must resolve the enhanced class.");

                /*
                 * Behavioral oracle.
                 */
                assertEquals(
                        17L,
                        ((Number) getId.invoke(restored))
                                .longValue(),
                        "id must survive the serialization round-trip.");

                assertEquals(
                        314159,
                        ((Number) getCounter.invoke(restored))
                                .intValue(),
                        "counter must survive the serialization round-trip.");

                assertEquals(
                        "SER-A",
                        getLabel.invoke(restored),
                        "label must survive the serialization round-trip.");
            }
        }
        finally {

            configuration.close();

            if (Files.exists(output)) {

                try (var stream =
                             Files.walk(output)) {

                    stream
                            .sorted(
                                    Comparator.reverseOrder())
                            .forEach(path -> {

                                try {
                                    Files.deleteIfExists(path);
                                }
                                catch (Exception ignored) {
                                    // Temporary test output cleanup.
                                }
                            });
                }
            }
        }
    }

    /**
     * Resolves the serialized target through the loader containing the
     * enhanced bytecode.
     */
    private static final class LoaderObjectInputStream
            extends ObjectInputStream {

        private final ClassLoader loader;

        private LoaderObjectInputStream(
                InputStream input,
                ClassLoader loader)
                throws IOException {

            super(input);

            this.loader =
                    loader;
        }

        @Override
        protected Class<?> resolveClass(
                java.io.ObjectStreamClass descriptor)
                throws IOException,
                ClassNotFoundException {

            try {

                return Class.forName(
                        descriptor.getName(),
                        false,
                        loader);

            }
            catch (ClassNotFoundException ignored) {

                return super.resolveClass(
                        descriptor);
            }
        }
    }

    /**
     * Only the purpose-built target is loaded child-first. All OpenJPA and
     * JDK classes continue to use the ordinary parent class loader.
     */
    private static final class ChildFirstTargetLoader
            extends URLClassLoader {

        private final String childFirstClass;

        private ChildFirstTargetLoader(
                URL[] urls,
                ClassLoader parent,
                String childFirstClass) {

            super(
                    urls,
                    parent);

            this.childFirstClass =
                    childFirstClass;
        }

        @Override
        protected Class<?> loadClass(
                String name,
                boolean resolve)
                throws ClassNotFoundException {

            synchronized (
                    getClassLoadingLock(name)) {

                Class<?> loaded =
                        findLoadedClass(name);

                if (
                    loaded == null
                    && name.equals(childFirstClass)
                ) {

                    try {

                        loaded =
                                findClass(name);

                    }
                    catch (ClassNotFoundException ignored) {
                        // Parent delegation below.
                    }
                }

                if (loaded == null) {

                    loaded =
                            super.loadClass(
                                    name,
                                    false);
                }

                if (resolve) {

                    resolveClass(
                            loaded);
                }

                return loaded;
            }
        }
    }
}