/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package it.uniroma2.isw2.openjpa.testing.pcenhancer.mt;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.lang.reflect.Method;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;

import org.apache.openjpa.conf.OpenJPAConfigurationImpl;
import org.apache.openjpa.enhance.PCEnhancer;
import org.apache.openjpa.enhance.PersistenceCapable;
import org.apache.openjpa.meta.ClassMetaData;
import org.apache.openjpa.persistence.JPAFacadeHelper;
import org.apache.openjpa.util.ObjectId;
import org.junit.jupiter.api.Test;

/**
 * TMT-001 - Application Identity runtime object-id semantics.
 *
 * <p>This test was introduced after mutation analysis of the frozen
 * T_BB + T_CF suite. It verifies the runtime behavior of the application
 * identity methods generated by PCEnhancer rather than only their presence
 * in the generated bytecode.</p>
 */
class PCEnhancerMutationIdentityTest {

    private static final String TARGET_NAME =
            PCEnhancerMutationIdentityTarget.class.getName();

    @Test
    void generatedApplicationIdentityMethodsPreserveRuntimeValues()
            throws Exception {

        OpenJPAConfigurationImpl configuration =
                new OpenJPAConfigurationImpl();

        Path output =
                Files.createTempDirectory(
                        "pcenhancer-tmt001-");

        try {
            configuration.setLog(
                    "File=stdout, DefaultLevel=WARN");

            configuration.setMetaDataFactory("jpa");

            ClassLoader fixtureLoader =
                    PCEnhancerMutationIdentityTarget
                            .class
                            .getClassLoader();

            ClassMetaData meta =
                    configuration
                            .getMetaDataRepositoryInstance()
                            .getMetaData(
                                    PCEnhancerMutationIdentityTarget.class,
                                    fixtureLoader,
                                    true);

            assertEquals(
                    ClassMetaData.ID_APPLICATION,
                    meta.getIdentityType(),
                    "The controlled fixture must use application identity.");

            PCEnhancer.Flags flags =
                    new PCEnhancer.Flags();

            flags.directory = output.toFile();
            flags.tmpClassLoader = false;

            boolean enhancementResult =
                    PCEnhancer.run(
                            configuration,
                            new String[]{TARGET_NAME},
                            flags,
                            null,
                            null,
                            fixtureLoader);

            assertTrue(
                    enhancementResult,
                    "PCEnhancer must successfully process the controlled target.");

            Path enhancedClass =
                    output.resolve(
                            TARGET_NAME.replace(
                                    '.',
                                    File.separatorChar)
                                    + ".class");

            assertTrue(
                    Files.isRegularFile(enhancedClass),
                    "Enhanced bytecode must be recorded.");

            try (ChildFirstTargetLoader loader =
                         new ChildFirstTargetLoader(
                                 new URL[]{output.toUri().toURL()},
                                 fixtureLoader,
                                 TARGET_NAME)) {

                Class<?> enhancedType =
                        Class.forName(
                                TARGET_NAME,
                                true,
                                loader);

                assertTrue(
                        PersistenceCapable.class
                                .isAssignableFrom(enhancedType),
                        "The enhanced target must implement PersistenceCapable.");

                Method setTenant =
                        enhancedType.getMethod(
                                "setTenantId",
                                int.class);

                Method setSequence =
                        enhancedType.getMethod(
                                "setSequenceId",
                                long.class);

                Method setExternal =
                        enhancedType.getMethod(
                                "setExternalCode",
                                String.class);

                Method getTenant =
                        enhancedType.getMethod(
                                "getTenantId");

                Method getSequence =
                        enhancedType.getMethod(
                                "getSequenceId");

                Method getExternal =
                        enhancedType.getMethod(
                                "getExternalCode");

                Method copyToObjectId =
                        enhancedType.getMethod(
                                "pcCopyKeyFieldsToObjectId",
                                Object.class);

                Method copyFromObjectId =
                        enhancedType.getMethod(
                                "pcCopyKeyFieldsFromObjectId",
                                Object.class);

                Method newObjectId =
                        enhancedType.getMethod(
                                "pcNewObjectIdInstance");

                // ------------------------------------------------
                // PC -> IdClass
                // ------------------------------------------------

                Object sourcePc =
                        enhancedType
                                .getDeclaredConstructor()
                                .newInstance();

                setTenant.invoke(sourcePc, 17);
                setSequence.invoke(sourcePc, 9000000007L);
                setExternal.invoke(sourcePc, "OID-A");

                PCEnhancerMutationIdentityTarget.Identity firstId =
                        new PCEnhancerMutationIdentityTarget.Identity();

                Object firstOpenJPAId =
                        JPAFacadeHelper.toOpenJPAObjectId(
                                meta,
                                firstId);

                assertInstanceOf(
                        ObjectId.class,
                        firstOpenJPAId,
                        "The application IdClass must be represented by an OpenJPA ObjectId.");

                copyToObjectId.invoke(
                        sourcePc,
                        firstOpenJPAId);

                assertEquals(
                        17,
                        firstId.tenantId,
                        "tenantId must be copied from the PC instance.");

                assertEquals(
                        9000000007L,
                        firstId.sequenceId,
                        "sequenceId must be copied from the PC instance.");

                assertEquals(
                        "OID-A",
                        firstId.externalCode,
                        "externalCode must be copied from the PC instance.");

                // ------------------------------------------------
                // IdClass -> fresh PC
                // ------------------------------------------------

                PCEnhancerMutationIdentityTarget.Identity secondId =
                        new PCEnhancerMutationIdentityTarget.Identity();

                secondId.tenantId = 41;
                secondId.sequenceId = 7000000003L;
                secondId.externalCode = "OID-B";

                Object secondOpenJPAId =
                        JPAFacadeHelper.toOpenJPAObjectId(
                                meta,
                                secondId);

                assertInstanceOf(
                        ObjectId.class,
                        secondOpenJPAId);

                Object destinationPc =
                        enhancedType
                                .getDeclaredConstructor()
                                .newInstance();

                copyFromObjectId.invoke(
                        destinationPc,
                        secondOpenJPAId);

                assertEquals(
                        41,
                        ((Number) getTenant.invoke(destinationPc))
                                .intValue(),
                        "tenantId must be copied back to the PC instance.");

                assertEquals(
                        7000000003L,
                        ((Number) getSequence.invoke(destinationPc))
                                .longValue(),
                        "sequenceId must be copied back to the PC instance.");

                assertEquals(
                        "OID-B",
                        getExternal.invoke(destinationPc),
                        "externalCode must be copied back to the PC instance.");

                // ------------------------------------------------
                // pcNewObjectIdInstance
                // ------------------------------------------------

                Object generatedInternalId =
                        newObjectId.invoke(destinationPc);

                assertInstanceOf(
                        ObjectId.class,
                        generatedInternalId,
                        "pcNewObjectIdInstance must create an OpenJPA ObjectId.");

                Object generatedUserId =
                        JPAFacadeHelper.fromOpenJPAObjectId(
                                generatedInternalId);

                assertInstanceOf(
                        PCEnhancerMutationIdentityTarget.Identity.class,
                        generatedUserId,
                        "The OpenJPA ObjectId must wrap the expected IdClass.");
            }
        }
        finally {
            configuration.close();

            if (Files.exists(output)) {
                try (var stream = Files.walk(output)) {
                    stream.sorted(Comparator.reverseOrder())
                            .forEach(path -> {
                                try {
                                    Files.deleteIfExists(path);
                                }
                                catch (Exception ignored) {
                                    // Temporary test output cleanup.
                                }
                            });
                }
            }
        }
    }

    private static final class ChildFirstTargetLoader
            extends URLClassLoader {

        private final String childFirstClass;

        private ChildFirstTargetLoader(
                URL[] urls,
                ClassLoader parent,
                String childFirstClass) {

            super(urls, parent);
            this.childFirstClass = childFirstClass;
        }

        @Override
        protected Class<?> loadClass(
                String name,
                boolean resolve)
                throws ClassNotFoundException {

            synchronized (getClassLoadingLock(name)) {

                Class<?> loaded =
                        findLoadedClass(name);

                if (loaded == null
                        && name.equals(childFirstClass)) {

                    try {
                        loaded = findClass(name);
                    }
                    catch (ClassNotFoundException ignored) {
                        // Delegate to the parent below.
                    }
                }

                if (loaded == null) {
                    loaded = super.loadClass(
                            name,
                            false);
                }

                if (resolve) {
                    resolveClass(loaded);
                }

                return loaded;
            }
        }
    }
}