/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package it.uniroma2.isw2.openjpa.testing.pcenhancer.mt;

import java.io.Serializable;
import java.util.Objects;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;

/**
 * Controlled target for TMT-001.
 *
 * <p>The fixture exposes composite application identity with three
 * distinguishable primary-key values so that the runtime semantics of the
 * identity methods generated by PCEnhancer can be observed.</p>
 */
@Entity
@IdClass(PCEnhancerMutationIdentityTarget.Identity.class)
public class PCEnhancerMutationIdentityTarget {

    @Id
    private int tenantId;

    @Id
    private long sequenceId;

    @Id
    private String externalCode;

    public PCEnhancerMutationIdentityTarget() {
    }

    public int getTenantId() {
        return tenantId;
    }

    public void setTenantId(int tenantId) {
        this.tenantId = tenantId;
    }

    public long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public String getExternalCode() {
        return externalCode;
    }

    public void setExternalCode(String externalCode) {
        this.externalCode = externalCode;
    }

    public static class Identity implements Serializable {

        private static final long serialVersionUID = 1L;

        public int tenantId;
        public long sequenceId;
        public String externalCode;

        public Identity() {
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) {
                return true;
            }

            if (!(other instanceof Identity that)) {
                return false;
            }

            return tenantId == that.tenantId
                    && sequenceId == that.sequenceId
                    && Objects.equals(externalCode, that.externalCode);
        }

        @Override
        public int hashCode() {
            return Objects.hash(
                    tenantId,
                    sequenceId,
                    externalCode);
        }
    }
}