/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package it.uniroma2.isw2.openjpa.testing.pcenhancer.mt;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Proxy;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import org.apache.openjpa.conf.OpenJPAConfigurationImpl;
import org.apache.openjpa.enhance.PCEnhancer;
import org.apache.openjpa.enhance.PersistenceCapable;
import org.apache.openjpa.enhance.StateManager;
import org.junit.jupiter.api.Test;

/**
 * TMT-004.
 *
 * Runtime verification of the PersistenceCapable / StateManager protocol
 * generated by PCEnhancer.
 */
class PCEnhancerMutationStateManagerTest {

    private static final String TARGET_NAME =
            PCEnhancerMutationStateManagerTarget.class.getName();

    @Test
    void generatedStateManagerProtocolPreservesManagedFieldSemantics()
            throws Exception {

        OpenJPAConfigurationImpl configuration =
                new OpenJPAConfigurationImpl();

        Path output =
                Files.createTempDirectory("pcenhancer-tmt004-");

        try {
            configuration.setLog("File=stdout, DefaultLevel=WARN");
            configuration.setMetaDataFactory("jpa");

            PCEnhancer enhancer =
                    new PCEnhancer(
                            configuration,
                            PCEnhancerMutationStateManagerTarget.class);

            enhancer.setDirectory(output.toFile());

            assertEquals(
                    PCEnhancer.ENHANCE_PC,
                    enhancer.run(),
                    "Target must be enhanced as PersistenceCapable.");

            enhancer.record();

            Path enhancedClass =
                    output.resolve(
                            TARGET_NAME.replace(
                                    '.',
                                    File.separatorChar)
                                    + ".class");

            assertTrue(
                    Files.isRegularFile(enhancedClass),
                    "Enhanced class must be recorded.");

            try (ChildFirstTargetLoader loader =
                         new ChildFirstTargetLoader(
                                 new URL[] { output.toUri().toURL() },
                                 PCEnhancerMutationStateManagerTarget.class
                                         .getClassLoader(),
                                 TARGET_NAME)) {

                Class<?> enhancedType =
                        Class.forName(
                                TARGET_NAME,
                                true,
                                loader);

                assertTrue(
                        PersistenceCapable.class
                                .isAssignableFrom(enhancedType),
                        "Enhanced class must implement PersistenceCapable.");

                Object instance =
                        enhancedType
                                .getDeclaredConstructor()
                                .newInstance();

                Method getId =
                        enhancedType.getMethod("getId");

                Method setId =
                        enhancedType.getMethod(
                                "setId",
                                long.class);

                Method getCounter =
                        enhancedType.getMethod("getCounter");

                Method setCounter =
                        enhancedType.getMethod(
                                "setCounter",
                                int.class);

                Method getLabel =
                        enhancedType.getMethod("getLabel");

                Method setLabel =
                        enhancedType.getMethod(
                                "setLabel",
                                String.class);

                /*
                 * ----------------------------------------------------------
                 * A. Managed-field count
                 * ----------------------------------------------------------
                 */

                Method managedCountMethod =
                        findMethod(
                                enhancedType,
                                "pcGetManagedFieldCount",
                                0);

                Object managedCountReceiver =
                        Modifier.isStatic(
                                managedCountMethod.getModifiers())
                                ? null
                                : instance;

                int managedCount =
                        ((Number) managedCountMethod.invoke(
                                managedCountReceiver))
                                .intValue();

                assertEquals(
                        3,
                        managedCount,
                        "Expected exactly three managed fields.");

                int[] fields =
                        new int[managedCount];

                for (int i = 0; i < managedCount; i++) {
                    fields[i] = i;
                }

                /*
                 * ----------------------------------------------------------
                 * B. Controlled StateManager
                 * ----------------------------------------------------------
                 */

                RecordingStateManager handler =
                        new RecordingStateManager();

                StateManager stateManager =
                        (StateManager) Proxy.newProxyInstance(
                                StateManager.class.getClassLoader(),
                                new Class<?>[] { StateManager.class },
                                handler);

                Method replaceStateManager =
                        findMethod(
                                enhancedType,
                                "pcReplaceStateManager",
                                1);

                Method getStateManager =
                        findMethod(
                                enhancedType,
                                "pcGetStateManager",
                                0);

                setId.invoke(instance, 17L);
                setCounter.invoke(instance, 314159);
                setLabel.invoke(instance, "STATE-A");

                replaceStateManager.invoke(
                        instance,
                        stateManager);

                assertSame(
                        stateManager,
                        getStateManager.invoke(instance),
                        "Assigned StateManager must be retained.");

                /*
                 * ----------------------------------------------------------
                 * C. pcProvideFields
                 * ----------------------------------------------------------
                 */

                Method provideFields =
                        findMethod(
                                enhancedType,
                                "pcProvideFields",
                                1);

                handler.beginProvide();

                provideFields.invoke(
                        instance,
                        (Object) fields);

                assertEquals(
                        3,
                        handler.providedValues.size(),
                        "All three managed fields must be provided.");

                assertTrue(
                        handler.providedValues.contains(17L),
                        "Long field value was not provided.");

                assertTrue(
                        handler.providedValues.contains(314159),
                        "Integer field value was not provided.");

                assertTrue(
                        handler.providedValues.contains("STATE-A"),
                        "String field value was not provided.");

                /*
                 * ----------------------------------------------------------
                 * D. pcReplaceFields
                 * ----------------------------------------------------------
                 */

                Method replaceFields =
                        findMethod(
                                enhancedType,
                                "pcReplaceFields",
                                1);

                handler.beginReplace();

                replaceFields.invoke(
                        instance,
                        (Object) fields);

                assertEquals(
                        1701L,
                        ((Number) getId.invoke(instance))
                                .longValue());

                assertEquals(
                        2718,
                        ((Number) getCounter.invoke(instance))
                                .intValue());

                assertEquals(
                        "STATE-B",
                        getLabel.invoke(instance));

                /*
                 * ----------------------------------------------------------
                 * E. pcCopyFields
                 * ----------------------------------------------------------
                 */

                Object donor =
                        enhancedType
                                .getDeclaredConstructor()
                                .newInstance();

                setId.invoke(donor, 8888L);
                setCounter.invoke(donor, 9999);
                setLabel.invoke(donor, "COPY-C");

                replaceStateManager.invoke(
                        donor,
                        stateManager);

                Method copyFields =
                        findMethod(
                                enhancedType,
                                "pcCopyFields",
                                2);

                copyFields.invoke(
                        instance,
                        donor,
                        fields);

                assertEquals(
                        8888L,
                        ((Number) getId.invoke(instance))
                                .longValue());

                assertEquals(
                        9999,
                        ((Number) getCounter.invoke(instance))
                                .intValue());

                assertEquals(
                        "COPY-C",
                        getLabel.invoke(instance));

                /*
                 * ----------------------------------------------------------
                 * F. pcNewInstance(StateManager, boolean)
                 * ----------------------------------------------------------
                 */

                Method newInstanceMethod =
                        findNewInstanceMethod(enhancedType);

                Object cleared =
                        newInstanceMethod.invoke(
                                instance,
                                stateManager,
                                true);

                assertNotNull(cleared);

                assertSame(
                        enhancedType,
                        cleared.getClass());

                assertSame(
                        stateManager,
                        getStateManager.invoke(cleared));

                assertEquals(
                        0L,
                        ((Number) getId.invoke(cleared))
                                .longValue());

                assertEquals(
                        0,
                        ((Number) getCounter.invoke(cleared))
                                .intValue());

                assertNull(
                        getLabel.invoke(cleared));

                /*
                 * clear=false must retain constructor initialization.
                 */
                Object uncleared =
                        newInstanceMethod.invoke(
                                instance,
                                stateManager,
                                false);

                assertNotNull(uncleared);

                assertSame(
                        stateManager,
                        getStateManager.invoke(uncleared));

                assertEquals(
                        101L,
                        ((Number) getId.invoke(uncleared))
                                .longValue());

                assertEquals(
                        202,
                        ((Number) getCounter.invoke(uncleared))
                                .intValue());

                assertEquals(
                        "CTOR",
                        getLabel.invoke(uncleared));

                System.out.println(
                        "TMT004_MANAGED_FIELDS:"
                                + managedCount);

                System.out.println(
                        "TMT004_PROVIDED:"
                                + handler.providedValues);

                System.out.println(
                        "TMT004_REPLACED:"
                                + 1701L
                                + ","
                                + 2718
                                + ",STATE-B");

                System.out.println(
                        "TMT004_COPIED:"
                                + getId.invoke(instance)
                                + ","
                                + getCounter.invoke(instance)
                                + ","
                                + getLabel.invoke(instance));

                System.out.println(
                        "TMT004_CLEAR_TRUE:"
                                + getId.invoke(cleared)
                                + ","
                                + getCounter.invoke(cleared)
                                + ","
                                + getLabel.invoke(cleared));

                System.out.println(
                        "TMT004_CLEAR_FALSE:"
                                + getId.invoke(uncleared)
                                + ","
                                + getCounter.invoke(uncleared)
                                + ","
                                + getLabel.invoke(uncleared));

                System.out.println(
                        "TMT004_RUNTIME:VALID");
            }
        }
        finally {
            configuration.close();

            if (Files.exists(output)) {
                try (var stream = Files.walk(output)) {
                    stream
                            .sorted(Comparator.reverseOrder())
                            .forEach(path -> {
                                try {
                                    Files.deleteIfExists(path);
                                }
                                catch (Exception ignored) {
                                    // Temporary output only.
                                }
                            });
                }
            }
        }
    }

    private static Method findMethod(
            Class<?> type,
            String name,
            int parameterCount) {

        Class<?> current = type;

        while (current != null) {
            for (Method method : current.getDeclaredMethods()) {
                if (method.getName().equals(name)
                        && method.getParameterCount() == parameterCount) {

                    method.setAccessible(true);
                    return method;
                }
            }

            current = current.getSuperclass();
        }

        throw new AssertionError(
                "Generated method not found: "
                        + name
                        + "/"
                        + parameterCount);
    }

    private static Method findNewInstanceMethod(
            Class<?> type) {

        Class<?> current = type;

        while (current != null) {
            for (Method method : current.getDeclaredMethods()) {
                if (!method.getName().equals("pcNewInstance")) {
                    continue;
                }

                Class<?>[] params =
                        method.getParameterTypes();

                if (params.length == 2
                        && StateManager.class
                                .isAssignableFrom(params[0])
                        && params[1] == boolean.class) {

                    method.setAccessible(true);
                    return method;
                }
            }

            current = current.getSuperclass();
        }

        throw new AssertionError(
                "pcNewInstance(StateManager, boolean) not found.");
    }

    private static final class RecordingStateManager
            implements InvocationHandler {

        private enum Mode {
            IDLE,
            PROVIDE,
            REPLACE
        }

        private Mode mode = Mode.IDLE;

        private final List<Object> providedValues =
                new ArrayList<>();

        void beginProvide() {
            providedValues.clear();
            mode = Mode.PROVIDE;
        }

        void beginReplace() {
            mode = Mode.REPLACE;
        }

        @Override
        public Object invoke(
                Object proxy,
                Method method,
                Object[] args) {

            String name = method.getName();

            if (method.getDeclaringClass() == Object.class) {
                if ("toString".equals(name)) {
                    return "TMT004-StateManager";
                }

                if ("hashCode".equals(name)) {
                    return System.identityHashCode(proxy);
                }

                if ("equals".equals(name)) {
                    return proxy == args[0];
                }
            }

            if (mode == Mode.PROVIDE
                    && name.startsWith("provided")
                    && args != null
                    && args.length >= 3) {

                providedValues.add(args[2]);
                return null;
            }

            if (mode == Mode.REPLACE
                    && name.startsWith("replace")) {

                Class<?> returnType =
                        method.getReturnType();

                if (returnType == long.class
                        || returnType == Long.class) {

                    return 1701L;
                }

                if (returnType == int.class
                        || returnType == Integer.class) {

                    return 2718;
                }

                if (returnType == String.class
                        || returnType == Object.class) {

                    return "STATE-B";
                }
            }

            Class<?> returnType =
                    method.getReturnType();

            if (returnType == void.class) {
                return null;
            }

            if (returnType == boolean.class) {
                return false;
            }

            if (returnType == byte.class) {
                return (byte) 0;
            }

            if (returnType == short.class) {
                return (short) 0;
            }

            if (returnType == int.class) {
                return 0;
            }

            if (returnType == long.class) {
                return 0L;
            }

            if (returnType == float.class) {
                return 0.0F;
            }

            if (returnType == double.class) {
                return 0.0D;
            }

            if (returnType == char.class) {
                return '\0';
            }

            return null;
        }
    }

    private static final class ChildFirstTargetLoader
            extends URLClassLoader {

        private final String childFirstClass;

        private ChildFirstTargetLoader(
                URL[] urls,
                ClassLoader parent,
                String childFirstClass) {

            super(urls, parent);
            this.childFirstClass = childFirstClass;
        }

        @Override
        protected Class<?> loadClass(
                String name,
                boolean resolve)
                throws ClassNotFoundException {

            synchronized (getClassLoadingLock(name)) {
                Class<?> loaded =
                        findLoadedClass(name);

                if (loaded == null
                        && name.equals(childFirstClass)) {

                    try {
                        loaded = findClass(name);
                    }
                    catch (ClassNotFoundException ignored) {
                        // Fall through to normal delegation.
                    }
                }

                if (loaded == null) {
                    loaded =
                            super.loadClass(
                                    name,
                                    false);
                }

                if (resolve) {
                    resolveClass(loaded);
                }

                return loaded;
            }
        }
    }
}