/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package it.uniroma2.isw2.openjpa.testing.pcenhancer.mt;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.Externalizable;
import java.io.File;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;

import org.apache.openjpa.conf.OpenJPAConfigurationImpl;
import org.apache.openjpa.enhance.PCEnhancer;
import org.apache.openjpa.enhance.PersistenceCapable;
import org.apache.openjpa.meta.ClassMetaData;
import org.junit.jupiter.api.Test;

/**
 * TMT-002 - Detached-state Externalization runtime round trip.
 *
 * <p>This test was introduced after mutation analysis of the suite
 * containing T_BB, T_CF and TMT-001. It verifies the actual runtime
 * semantics of the Externalizable support generated by PCEnhancer.</p>
 */
class PCEnhancerMutationExternalizationTest {

    private static final String TARGET_NAME =
            PCEnhancerMutationExternalizationTarget.class.getName();

    @Test
    void generatedExternalizationMethodsPreserveRuntimeState()
            throws Exception {

        OpenJPAConfigurationImpl configuration =
                new OpenJPAConfigurationImpl();

        Path output =
                Files.createTempDirectory(
                        "pcenhancer-tmt002-");

        try {
            configuration.setLog(
                    "File=stdout, DefaultLevel=WARN");

            configuration.setMetaDataFactory(
                    "jpa");

            configuration.setDetachState(
                    "fetch-groups(DetachedStateField=true)");

            PCEnhancer enhancer =
                    new PCEnhancer(
                            configuration,
                            PCEnhancerMutationExternalizationTarget.class);

            ClassMetaData metadata =
                    enhancer.getMetaData();

            assertNotNull(
                    metadata,
                    "Metadata must be available.");

            assertEquals(
                    ClassMetaData.SYNTHETIC,
                    metadata.getDetachedState(),
                    "The fixture must use synthetic detached state.");

            assertFalse(
                    configuration
                            .getDetachStateInstance()
                            .isDetachedStateTransient(),
                    "Detached state must participate in externalization.");

            enhancer.setDirectory(
                    output.toFile());

            assertEquals(
                    PCEnhancer.ENHANCE_PC,
                    enhancer.run(),
                    "The controlled target must require PC enhancement.");

            enhancer.record();

            Path enhancedClass =
                    output.resolve(
                            TARGET_NAME.replace(
                                    '.',
                                    File.separatorChar)
                                    + ".class");

            assertTrue(
                    Files.isRegularFile(enhancedClass),
                    "Enhanced bytecode must be recorded.");

            try (ChildFirstTargetLoader loader =
                         new ChildFirstTargetLoader(
                                 new URL[]{
                                         output.toUri().toURL()
                                 },
                                 PCEnhancerMutationExternalizationTarget
                                         .class
                                         .getClassLoader(),
                                 TARGET_NAME)) {

                Class<?> enhancedType =
                        Class.forName(
                                TARGET_NAME,
                                true,
                                loader);

                assertTrue(
                        PersistenceCapable.class
                                .isAssignableFrom(enhancedType),
                        "Enhanced target must implement PersistenceCapable.");

                assertTrue(
                        Externalizable.class
                                .isAssignableFrom(enhancedType),
                        "Enhanced target must implement Externalizable.");

                var setId =
                        enhancedType.getMethod(
                                "setId",
                                long.class);

                var setCounter =
                        enhancedType.getMethod(
                                "setCounter",
                                int.class);

                var setLabel =
                        enhancedType.getMethod(
                                "setLabel",
                                String.class);

                var getId =
                        enhancedType.getMethod(
                                "getId");

                var getCounter =
                        enhancedType.getMethod(
                                "getCounter");

                var getLabel =
                        enhancedType.getMethod(
                                "getLabel");

                var setDetachedState =
                        enhancedType.getMethod(
                                "pcSetDetachedState",
                                Object.class);

                var getDetachedState =
                        enhancedType.getMethod(
                                "pcGetDetachedState");

                /*
                 * SOURCE
                 */
                Object source =
                        enhancedType
                                .getDeclaredConstructor()
                                .newInstance();

                setId.invoke(
                        source,
                        17L);

                setCounter.invoke(
                        source,
                        314159);

                setLabel.invoke(
                        source,
                        "EXT-A");

                setDetachedState.invoke(
                        source,
                        "DETACHED-A");

                /*
                 * writeExternal -> real byte stream
                 */
                byte[] payload;

                try (ByteArrayOutputStream bytes =
                             new ByteArrayOutputStream();
                     ObjectOutputStream out =
                             new ObjectOutputStream(bytes)) {

                    ((Externalizable) source)
                            .writeExternal(out);

                    out.flush();

                    payload =
                            bytes.toByteArray();
                }

                assertTrue(
                        payload.length > 0,
                        "writeExternal must produce a non-empty payload.");

                /*
                 * Fresh destination with clearly different sentinel values.
                 */
                Object destination =
                        enhancedType
                                .getDeclaredConstructor()
                                .newInstance();

                setId.invoke(
                        destination,
                        -1L);

                setCounter.invoke(
                        destination,
                        -2);

                setLabel.invoke(
                        destination,
                        "BEFORE");

                setDetachedState.invoke(
                        destination,
                        "BEFORE-STATE");

                /*
                 * real byte stream -> readExternal
                 */
                try (ObjectInputStream in =
                             new ObjectInputStream(
                                     new ByteArrayInputStream(
                                             payload))) {

                    ((Externalizable) destination)
                            .readExternal(in);
                }

                /*
                 * Behavioral oracle.
                 */
                assertEquals(
                        17L,
                        ((Number)
                                getId.invoke(destination))
                                .longValue(),
                        "id must survive the externalization round trip.");

                assertEquals(
                        314159,
                        ((Number)
                                getCounter.invoke(destination))
                                .intValue(),
                        "counter must survive the externalization round trip.");

                assertEquals(
                        "EXT-A",
                        getLabel.invoke(destination),
                        "label must survive the externalization round trip.");

                assertEquals(
                        "DETACHED-A",
                        getDetachedState.invoke(destination),
                        "synthetic detached state must survive the round trip.");
            }
        }
        finally {
            configuration.close();

            if (Files.exists(output)) {

                try (var stream =
                             Files.walk(output)) {

                    stream.sorted(
                                    Comparator.reverseOrder())
                            .forEach(path -> {
                                try {
                                    Files.deleteIfExists(path);
                                }
                                catch (Exception ignored) {
                                    // Temporary test output cleanup.
                                }
                            });
                }
            }
        }
    }

    private static final class ChildFirstTargetLoader
            extends URLClassLoader {

        private final String childFirstClass;

        private ChildFirstTargetLoader(
                URL[] urls,
                ClassLoader parent,
                String childFirstClass) {

            super(
                    urls,
                    parent);

            this.childFirstClass =
                    childFirstClass;
        }

        @Override
        protected Class<?> loadClass(
                String name,
                boolean resolve)
                throws ClassNotFoundException {

            synchronized (
                    getClassLoadingLock(name)) {

                Class<?> loaded =
                        findLoadedClass(name);

                if (loaded == null
                        && name.equals(
                                childFirstClass)) {

                    try {
                        loaded =
                                findClass(name);
                    }
                    catch (
                            ClassNotFoundException ignored) {
                        // Delegate below.
                    }
                }

                if (loaded == null) {

                    loaded =
                            super.loadClass(
                                    name,
                                    false);
                }

                if (resolve) {

                    resolveClass(
                            loaded);
                }

                return loaded;
            }
        }
    }
}